//
//  UIFont+GLSAdditions.swift
//
//  Generated by Zeplin on 3/23/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {
	class func glsSketchTitleFont() -> UIFont? {
		return UIFont(name: "Lato-Black", size: 48.0)
	}

	class func glsCameraTextFont() -> UIFont? {
		return UIFont(name: "Lato-Light", size: 36.0)
	}
}
